//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PortAIO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PortAIO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        internal static byte[] _6_8
        {
            get
            {
                object obj = ResourceManager.GetObject("_6_8", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Injected.
        /// </summary>
        internal static string Corki_Game_OnGameLoad_Injected {
            get {
                return ResourceManager.GetString("Corki_Game_OnGameLoad_Injected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Loaded.
        /// </summary>
        internal static string Corki_Initialize_Menu_Loaded {
            get {
                return ResourceManager.GetString("Corki_Initialize_Menu_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap denymouse {
            get {
                object obj = ResourceManager.GetObject("denymouse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Loaded.
        /// </summary>
        internal static string Diana_Initialize_Menu_Loaded {
            get {
                return ResourceManager.GetString("Diana_Initialize_Menu_Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                _,........__
        ///            ,-&apos;            &quot;`-.
        ///          ,&apos;                   `-.
        ///        ,&apos;                        \
        ///      ,&apos;                           .
        ///      .&apos;\               ,&quot;&quot;.       `
        ///     ._.&apos;|             / |  `       \
        ///     |   |            `-.&apos;  ||       `.
        ///     |   |            &apos;-._,&apos;||       | \
        ///     .`.,&apos;             `..,&apos;.&apos;       , |`-.
        ///     l                       .&apos;`.  _/  |   `.
        ///     `-.._&apos;-   ,          _ _&apos;   -&quot; \  .     `
        ///`.&quot;&quot;&quot;&quot;&quot;&apos;-.`-...,---------&apos;,&apos;         `. `....__.
        ///.&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string display {
            get {
                return ResourceManager.GetString("display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to            _.--&quot;&quot;`-..
        ///            ,&apos;          `.
        ///          ,&apos;          __  `.
        ///         /|          &quot; __   \
        ///        , |           / |.   .
        ///        |,&apos;          !_.&apos;|   |
        ///      ,&apos;             &apos;   |   |
        ///     /              |`--&apos;|   |
        ///    |                `---&apos;   |
        ///     .   ,                   |                       ,&quot;.
        ///      ._     &apos;           _&apos;  |                    , &apos; \ `
        ///  `.. `.`-...___,...---&quot;&quot;    |       __,.        ,`&quot;   L,|
        ///  |, `- .`._        _,-,.&apos;   .  __.-&apos;-. /        .   ,    \
        ///-:..     `. `-. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string display2 {
            get {
                return ResourceManager.GetString("display2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to                                                   /
        ///                        _,.------....___,.&apos; &apos;,.-.
        ///                     ,-&apos;          _,.--&quot;        |
        ///                   ,&apos;         _.-&apos;              .
        ///                  /   ,     ,&apos;                   `
        ///                 .   /     /                     ``.
        ///                 |  |     .                       \.\
        ///       ____      |___._.  |       __               \ `.
        ///     .&apos;    `---&quot;&quot;       ``&quot;-.--&quot;&apos;`  \               .  \
        ///    .  ,            __               `  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string display3 {
            get {
                return ResourceManager.GetString("display3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap intro {
            get {
                object obj = ResourceManager.GetObject("intro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimap_Ward_Green_Enemy {
            get {
                object obj = ResourceManager.GetObject("Minimap_Ward_Green_Enemy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Minimap_Ward_Pink_Enemy {
            get {
                object obj = ResourceManager.GetObject("Minimap_Ward_Pink_Enemy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mouse1 {
            get {
                object obj = ResourceManager.GetObject("mouse1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mouse2 {
            get {
                object obj = ResourceManager.GetObject("mouse2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initialitzing TheBrand: .
        /// </summary>
        internal static string Program_Load_Error_initialitzing_TheBrand__ {
            get {
                return ResourceManager.GetString("Program_Load_Error_initialitzing_TheBrand__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RecallBar {
            get {
                object obj = ResourceManager.GetObject("RecallBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScopeSprite {
            get {
                object obj = ResourceManager.GetObject("ScopeSprite", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _6_7
        {
            get
            {
                object obj = ResourceManager.GetObject("_6_7", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cursor_drag
        {
            get
            {
                object obj = ResourceManager.GetObject("cursor_drag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Gapclosers
        {
            get
            {
                object obj = ResourceManager.GetObject("Gapclosers", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notifications_arrow
        {
            get
            {
                object obj = ResourceManager.GetObject("notifications_arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notifications_check
        {
            get
            {
                object obj = ResourceManager.GetObject("notifications_check", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notifications_error
        {
            get
            {
                object obj = ResourceManager.GetObject("notifications_error", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notifications_select
        {
            get
            {
                object obj = ResourceManager.GetObject("notifications_select", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notifications_star
        {
            get
            {
                object obj = ResourceManager.GetObject("notifications_star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap notifications_warning
        {
            get
            {
                object obj = ResourceManager.GetObject("notifications_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

    }
}
